server:
    port: 8081
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: password
        url: jdbc:mysql://localhost:3306/db_warehouse?useUnicode=true&characterEncoding=UTF-8&useSSL=false
        username: root
    servlet:
      multipart:
          max-file-size: 1000MB
          max-request-size: 1000MB